name: raw_data_processing
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.11
  - pywin32=308
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
